##1.	Display all customers who live in 'Delhi'.
select distinct name from customers
where city = 'Delhi';

##2.	Find the average rating of all restaurants in 'Mumbai'.
select distinct name,
avg(rating), city 
from restaurants
where city = 'Mumbai' and rating is not null
group by name, city;

##3.	List all customers who have placed at least one order.
select distinct name, count(order_id) as Order_count
from customers
join orders 
using(customer_id)
group by name
having count(order_id) > 1;

##4.	Display the total number of orders placed by each customer.
select distinct name, count(order_id) as total_orders
from customers
join orders 
using(customer_id)
group by name;

##5.	Find the total revenue generated by each restaurant.
select restaurants.name, sum(total_amount) as revenue 
from restaurants
join orders
using (restaurant_id)
group by restaurants.name;
 
##6.	Find the top 5 restaurants with the highest average rating.
select distinct name, rating 
from restaurants
order by rating desc
limit 5;
 
##7.	Display all customers who have never placed an order.
select distinct name  from customers
where customer_id not in (select customer_id from orders);
##or
select distinct name
from customers
left join orders using(customer_id)
where orders.customer_id is null;

##8.	Find the number of orders placed by each customer in 'Mumbai'.
select distinct  name, count(order_id) as order_count
from orders
join customers using (customer_id)
where city = 'Mumbai'
group by name;

##9.	Display all orders placed in the last 30 days.
SELECT * 
FROM orders
WHERE order_date >= (SELECT DATE_SUB(MAX(order_date), INTERVAL 30 DAY) FROM orders);

##10.	List all delivery partners who have completed more than 1 delivery
select distinct name, count(order_delivery_id) as deliverycount
from deliverypartners
join orderdelivery
using (partner_id)
group by name
having count(order_delivery_id)  > 1 
order by deliverycount desc;

##11.	Find the customers who have placed orders on exactly three different days.
select distinct name
from orders
join customers
using (customer_id)
group by name 
having count(distinct(order_date)) = 3;

##12.	Find the delivery partner who has worked with the most different customers.
select name as delivery_partner,
COUNT(distinct customer_id) as unique_customers
from deliverypartners 
join orderdelivery using (partner_id)
join orders using (order_id)
group by name
order by unique_customers desc
limit 1;

##13.	Identify customers who have the same city and have placed orders at the same restaurants, but on different dates.
SELECT DISTINCT c1.name AS customer1, c2.name AS customer2, 
c1.city, o1.restaurant_id, r.name, o1.order_date as orderdate1, o2.order_date as orderdate2
FROM customers c1
JOIN orders o1 USING(customer_id)
JOIN customers c2 ON c1.city = c2.city AND c1.customer_id < c2.customer_id or c1.customer_id > c2.customer_id
JOIN orders o2 ON c2.customer_id = o2.customer_id 
               AND o1.restaurant_id = o2.restaurant_id
               AND DATE(o1.order_date) != DATE(o2.order_date)
join restaurants r on r.restaurant_id = o1.restaurant_id;



